ttf2pt1.exe -a arial.ttf san_arial
ttf2pt1.exe -a arialbd.ttf san_arialbd
ttf2pt1.exe -a arialbi.ttf san_arialbi
ttf2pt1.exe -a ariali.ttf san_ariali
ttf2pt1.exe -a ARIALN.TTF san_ARIALN
ttf2pt1.exe -a ARIALNB.TTF san_ARIALNB
ttf2pt1.exe -a ARIALNBI.TTF san_ARIALNBI
ttf2pt1.exe -a ARIALNI.TTF san_ARIALNI
ttf2pt1.exe -a ariblk.ttf san_ariblk
ttf2pt1.exe -a tahomabd.ttf tahomabd
ttf2pt1.exe -a verdanab.ttf verdanab
ttf2pt1.exe -a verdanai.ttf verdanai
ttf2pt1.exe -a verdanaz.ttf verdanaz